# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image: atlassian/default-image:2
image: aergus/latex

pipelines:
  default:
    - step:
        name: Build
        script:
          # BUILDING
          - echo "Creating PDF"
          - make
    - step:
        name: Notifications
        script:    
          # NOTIFICATIONS
          - echo "Sending email notification"
          - pipe: atlassian/email-notify:0.3.8
            variables:
              USERNAME: 'spataro.davide@gmx.com'
              PASSWORD: 'AwV5ou3DqiLm'
              FROM: 'spataro.davide@gmx.com'
              TO: 'davide90.spataro@gmail.com'
              HOST: 'mail.gmx.com'
              PORT: '587' # Optional.
              TLS: 'true' # Optional.
              SUBJECT: '[BITBUCKET][BOOK] New Build'
              ATTACHMENTS: 'build/main.pdf' 
              BODY_PLAIN: 'A new successful build has been performed. Attached the Book PDF'
              # BODY_HTML: '<string>'
              # DEBUG: '<boolean>'
          - pipe: atlassian/email-notify:0.3.8
            variables:
              USERNAME: 'spataro.davide@gmx.com'
              PASSWORD: 'AwV5ou3DqiLm'
              FROM: 'spataro.davide@gmx.com'
              TO: 'pranav656@gmail.com '
              HOST: 'mail.gmx.com'
              PORT: '587' # Optional.
              TLS: 'true' # Optional.
              SUBJECT: '[BITBUCKET][BOOK] New Build'
              ATTACHMENTS: 'build/main.pdf' 
              BODY_PLAIN: 'A new successful build has been performed. Attached the Book PDF'
              # BODY_HTML: '<string>'
              # DEBUG: '<boolean>'