 version: 2
 jobs:
   build:
     docker:
       - image: aergus/latex
     steps:
       - run: echo "Install software"
       - run: apt-get update -qq
       - run: apt-get install -qq -y cmake
       - run: apt-get install -qq -y build-essential
       - run: git clone --depth=1 -b master -q https://github.com/google/googletest.git /googletest
       - run: mkdir -p /googletest/build
       - run: cd /googletest/build && cmake .. && make && make install
       - run: rm -rf /googletest
       - run: echo "Creating PDF and Building UTs"
       - checkout
       - run: make fullpdf tests
       - run: bash run_all_tests.sh